### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by caoxu915683474** [LuJunru/Sentences_Pair_Similarity_Calculation_Siamese_LSTM#1]
谢谢分享！这里的翻译和中文不都指的 Quora 数据对应的中文吗？
另外想问下，蚂蚁金服的你也尝试翻译了吗？

**Comment by LuJunru** [comment]
不好意思，才看到，翻译指的是Quora，蚂蚁金服没有尝试翻译

**Comment by LuJunru** [comment]
> 谢谢分享！这里的翻译和中文不都指的 Quora 数据对应的中文吗？
> 另外想问下，蚂蚁金服的你也尝试翻译了吗？

不好意思，才看到，翻译指的是Quora，蚂蚁金服没有尝试翻译
