### ISSUE TITLE
A Keras Implementation of Attention_based Siamese Manhattan LSTM

### ISSUE THREAD

**Issue by haorans1994** [LuJunru/Sentences_Pair_Similarity_Calculation_Siamese_LSTM#5]
Hey Junru

我叫孙浩然。我在查怎么构造Siamese模型的时候在github伤看到了你的代码。你使用keras做的。我基本复制了你的代码，然后在本地做，但是略有不同。
我没用embedding层，而是直接：
activations = Bidirectional(LSTM(n_hidden, return_sequences=True), merge_mode='concat')(_input)
activations = Bidirectional(LSTM(n_hidden, return_sequences=True), merge_mode='concat')(activations)
原因稍后讲。然后我将输入的数据直接变成了【【0.21，0.2135..。0.2354】【0.33，0.26..0.25】【0.235,0.235...0.235】】用的glove100d。 简单说就是我把embedding层的计算移到外面了。直接把word变成vector。
然后做出来validation是80%左右，跟你的original的代码差不多。然后我保存了model，然后，因为我有glove100d，所以我直接放了几个自己临时写的句子然后把他们转化成相同的input shape：
model = load_model('my_10length_model.h5', custom_objects={'ManDist': ManDist})
texttarget = ['How do I make friends?']
text1 = ['How to make friends?']
text2 = ['Can you tell me how to play the piano?']
text3 = ['Can you tell me the truth of the computer games?']
texttarget = prepare_data(texttarget,MAX_SEQ_LENGTH,embeddings_index)
candidate_1 = prepare_data(text1,MAX_SEQ_LENGTH,embeddings_index)
candidate_2 = prepare_data(text2,MAX_SEQ_LENGTH,embeddings_index)
candidate_3 = prepare_data(text3,MAX_SEQ_LENGTH,embeddings_index)
# print(texttarget)

result1 = model.predict([texttarget,candidate_1])
result2 = model.predict([texttarget,candidate_2])
result3 = model.predict([texttarget,candidate_3])
print(result1,result2,result3)
然后result是：
[[0.5311898]] [[0.60761184]] [[0.42349315]]
其中的prepare_data函数是把任意句子通过glove转化成一个有MAX_SEQ_LENGTH个100维的vector的list。
从结果我们可以看出，这个模型认为第二句跟我的target句子是最相似的。进一步说明，这个模型实际上根本不具有普遍性，没办法真正计算任意句子的相似度。
我给你发issue的目的是想问问，你有没有更好的办法可以提高模型对非训练集的句子pair的计算相似度的准确率？

cheers
Haoran

**Comment by LuJunru** [comment]
@haorans1994 
Hi 浩然，

不好意思这么晚才看到。你的分析很对，我建议直接把embedding改用bert/XLnet试一下。

best,
Junru
